//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IshalInc.wJewel.Desktop.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IshalInc.wJewel.Desktop.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap admin {
            get {
                object obj = ResourceManager.GetObject("admin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap auto_apply {
            get {
                object obj = ResourceManager.GetObject("auto_apply", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cancel {
            get {
                object obj = ResourceManager.GetObject("cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap customeredit {
            get {
                object obj = ResourceManager.GetObject("customeredit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap customerlist {
            get {
                object obj = ResourceManager.GetObject("customerlist", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap customernew {
            get {
                object obj = ResourceManager.GetObject("customernew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap customers {
            get {
                object obj = ResourceManager.GetObject("customers", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer details deleted successfully.
        /// </summary>
        internal static string Delete_Successful_Message {
            get {
                return ResourceManager.GetString("Delete_Successful_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete successfull.
        /// </summary>
        internal static string Delete_Successful_Message_Title {
            get {
                return ResourceManager.GetString("Delete_Successful_Message_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dollar {
            get {
                object obj = ResourceManager.GetObject("dollar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit {
            get {
                object obj = ResourceManager.GetObject("edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap element_add {
            get {
                object obj = ResourceManager.GetObject("element_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the following..
        /// </summary>
        internal static string Error_Message_Header {
            get {
                return ResourceManager.GetString("Error_Message_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exit {
            get {
                object obj = ResourceManager.GetObject("exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string Export_Button_Text {
            get {
                return ResourceManager.GetString("Export_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap invoice_add {
            get {
                object obj = ResourceManager.GetObject("invoice_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap invoice_delete {
            get {
                object obj = ResourceManager.GetObject("invoice_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap invoice_edit {
            get {
                object obj = ResourceManager.GetObject("invoice_edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap invoicereport {
            get {
                object obj = ResourceManager.GetObject("invoicereport", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login_Login_Button_Text {
            get {
                return ResourceManager.GetString("Login_Login_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string Login_Password_Label_Text {
            get {
                return ResourceManager.GetString("Login_Password_Label_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        internal static string Login_Username_Label_Text {
            get {
                return ResourceManager.GetString("Login_Username_Label_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid username and password..
        /// </summary>
        internal static string Login_Validation_Message {
            get {
                return ResourceManager.GetString("Login_Validation_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login - Message.
        /// </summary>
        internal static string Login_Validation_Message_Title {
            get {
                return ResourceManager.GetString("Login_Validation_Message_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mail {
            get {
                object obj = ResourceManager.GetObject("mail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap memo {
            get {
                object obj = ResourceManager.GetObject("memo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap memoreport {
            get {
                object obj = ResourceManager.GetObject("memoreport", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;root&gt;
        ///	
        ///  &lt;TopLevelMenu Name=&quot;20&quot; Text=&quot;Customer&quot; image=&quot;customers&quot;&gt;
        ///    &lt;MenuItem Name=&quot;201&quot; Text=&quot;New Customer&quot; OnClick=&quot;F:frmAccountCode&quot; image=&quot;customernew&quot; Type=&quot;Form&quot;/&gt;
        ///    &lt;MenuItem Name=&quot;202&quot; Text=&quot;Edit Customer&quot; OnClick=&quot;F:frmSearchCustomer&quot; image=&quot;customeredit&quot; Type=&quot;Form&quot;/&gt;
        ///    &lt;MenuItem Name=&quot;203&quot; Text=&quot;Add Potential Customer &quot; OnClick=&quot;F:frmAddpotenialCustomer&quot; image=&quot;customernew&quot; Type=&quot;Form&quot;/&gt;
        ///    &lt;MenuItem Name=&quot;204&quot; Text=&quot;Edit Potential Customer &quot; OnClick=&quot;F:frmSearchPotentialCustomer [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OK {
            get {
                object obj = ResourceManager.GetObject("OK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string Print_Print_Button_Text {
            get {
                return ResourceManager.GetString("Print_Print_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print preview.
        /// </summary>
        internal static string Print_PrintPreview_Button_Text {
            get {
                return ResourceManager.GetString("Print_PrintPreview_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap printer {
            get {
                object obj = ResourceManager.GetObject("printer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. of children.
        /// </summary>
        internal static string Registration_Children_Label_Text {
            get {
                return ResourceManager.GetString("Registration_Children_Label_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth.
        /// </summary>
        internal static string Registration_DateOfBirth_Label_Text {
            get {
                return ResourceManager.GetString("Registration_DateOfBirth_Label_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration failed.
        /// </summary>
        internal static string Registration_Error_Message {
            get {
                return ResourceManager.GetString("Registration_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration error.
        /// </summary>
        internal static string Registration_Error_Message_Title {
            get {
                return ResourceManager.GetString("Registration_Error_Message_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health status.
        /// </summary>
        internal static string Registration_HealthStatus_Label_Text {
            get {
                return ResourceManager.GetString("Registration_HealthStatus_Label_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select health status..
        /// </summary>
        internal static string Registration_HealthStatus_Select_Text {
            get {
                return ResourceManager.GetString("Registration_HealthStatus_Select_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marital status.
        /// </summary>
        internal static string Registration_MaritalStatus_Label_Text {
            get {
                return ResourceManager.GetString("Registration_MaritalStatus_Label_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select marital status..
        /// </summary>
        internal static string Registration_MaritalStatus_Select_Text {
            get {
                return ResourceManager.GetString("Registration_MaritalStatus_Select_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Registration_Name_Label_Text {
            get {
                return ResourceManager.GetString("Registration_Name_Label_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required..
        /// </summary>
        internal static string Registration_Name_Required_Text {
            get {
                return ResourceManager.GetString("Registration_Name_Required_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupation.
        /// </summary>
        internal static string Registration_Occupation_Label_Text {
            get {
                return ResourceManager.GetString("Registration_Occupation_Label_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a occupation..
        /// </summary>
        internal static string Registration_Occupation_Select_Text {
            get {
                return ResourceManager.GetString("Registration_Occupation_Select_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Registration_Register_Button_Text {
            get {
                return ResourceManager.GetString("Registration_Register_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary.
        /// </summary>
        internal static string Registration_Salary_Label_Text {
            get {
                return ResourceManager.GetString("Registration_Salary_Label_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New customer registered successfully!.
        /// </summary>
        internal static string Registration_Successful_Message {
            get {
                return ResourceManager.GetString("Registration_Successful_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Successful.
        /// </summary>
        internal static string Registration_Successful_Message_Title {
            get {
                return ResourceManager.GetString("Registration_Successful_Message_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap report {
            get {
                object obj = ResourceManager.GetObject("report", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jewelry Software - Customers.
        /// </summary>
        internal static string Report_Header {
            get {
                return ResourceManager.GetString("Report_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search {
            get {
                object obj = ResourceManager.GetObject("search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Search_Refresh_Button_Text {
            get {
                return ResourceManager.GetString("Search_Refresh_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search_Search_Button_Text {
            get {
                return ResourceManager.GetString("Search_Search_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search1 {
            get {
                object obj = ResourceManager.GetObject("search1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;SearchFields&gt;
        ///  &lt;SearchFieldsRow&gt;
        ///    &lt;sid&gt;BillAccountSearch&lt;/sid&gt;
        ///    &lt;FieldName&gt;bill_acc&lt;/FieldName&gt;
        ///    &lt;FieldCaption&gt;Billing Acct #&lt;/FieldCaption&gt;
        ///    &lt;FieldWidth&gt;70&lt;/FieldWidth&gt;
        ///  &lt;/SearchFieldsRow&gt;
        ///  &lt;SearchFieldsRow&gt;
        ///    &lt;sid&gt;BillAccountSearch&lt;/sid&gt;
        ///    &lt;FieldName&gt;name&lt;/FieldName&gt;
        ///    &lt;FieldCaption&gt;Name&lt;/FieldCaption&gt;
        ///    &lt;FieldWidth&gt;100&lt;/FieldWidth&gt;
        ///  &lt;/SearchFieldsRow&gt;
        ///  &lt;SearchFieldsRow&gt;
        ///    &lt;sid&gt;BillAccountSearch&lt;/sid&gt;
        ///    &lt;FieldName&gt;Tel&lt;/F [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SearchFields {
            get {
                return ResourceManager.GetString("SearchFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap searchnew {
            get {
                object obj = ResourceManager.GetObject("searchnew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap soi {
            get {
                object obj = ResourceManager.GetObject("soi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap statementofmemo {
            get {
                object obj = ResourceManager.GetObject("statementofmemo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap styletracking {
            get {
                object obj = ResourceManager.GetObject("styletracking", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! System error. Please contact administrator..
        /// </summary>
        internal static string System_Error_Message {
            get {
                return ResourceManager.GetString("System_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error - Message.
        /// </summary>
        internal static string System_Error_Message_Title {
            get {
                return ResourceManager.GetString("System_Error_Message_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap undo {
            get {
                object obj = ResourceManager.GetObject("undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update_Button_Text {
            get {
                return ResourceManager.GetString("Update_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update error.
        /// </summary>
        internal static string Update_Error_Message_Title {
            get {
                return ResourceManager.GetString("Update_Error_Message_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer details updated successfully.
        /// </summary>
        internal static string Update_Successful_Message {
            get {
                return ResourceManager.GetString("Update_Successful_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update successfull.
        /// </summary>
        internal static string Update_Successful_Message_Title {
            get {
                return ResourceManager.GetString("Update_Successful_Message_Title", resourceCulture);
            }
        }
    }
}
